### ISSUE TITLE
Compatibility with current StudentWeb

### ISSUE THREAD

**Issue by tobiasvl** [tobiasvl/studweb#2]
Do we actually support the current version of StudentWeb? Who knows? @jasama is currently a student, maybe you can check for us? It would be nice to support the grades coming at the end of this semester

**Comment by fatso83** [comment]
You can use the dumped html found in [test/testdata](http://github.com/fatso83/studweb). Other than that, you might browse my comment in [this thread](http://www.diskusjon.no/index.php?showtopic=894489&page=2). Perhaps we could merge some code? Seems like you might be in need of some unit and regression tests :-)

**Comment by tobiasvl** [comment]
:+1:

**Comment by tobiasvl** [comment]
@fatso83 Som IT-ansatt på UiO misliker jeg at ditt prosjekt oppfordrer til lagring av UiO-passord (til SMTP-autentisering) på hjemmeområdet, men ellers ser det veldig fint ut! Mitt prosjekt er et gammelt og utdatert hack, så ditt er sikkert bedre på alle andre måter :wink:

**Comment by fatso83** [comment]
Forstår bekymringen, og mottar gjerne forslag på hvordan man kan komme utenom det. Hashing går jo ikke, så det blir i beste fall et reverserbart cipher. Kan gjerne fjerne UiO-spesifiseringen, og heller nevne Gmail eller noe sånt. I det minste nekter programmet å kjøre om fila kan leses av andre enn brukeren selv :-)

**Comment by jasama** [comment]
On 06 Jan 2015, at 17:12, Carl-Erik Kopseng <notifications@github.com<mailto:notifications@github.com>> wrote:


Forst?r bekymringen, og mottar gjerne forslag p? hvordan man kan komme utenom det. Hashing g?r jo ikke, s? det blir i beste fall et reverserbart cipher. Kan gjerne fjerne UiO-spesifiseringen, og heller nevne Gmail eller noe s?nt. I det minste nekter programmet ? kj?re om fila kan leses av andre enn brukeren selv :-)

-
Reply to this email directly or view it on GitHub<https://github.com/tobiasvl/studweb/issues/2#issuecomment-68886398>.

Et alternativ kan vaere ? lese inn brukernavn og passord interaktivt p? start, og deretter g? i daemon-modus. Da slipper man ? lagre brukernavn og passord i noe annet medium en minnet. Bakdelen er at man m? starte programmet p? nytt manuelt hver gang man snubler i ledningen.

(A)symmetrisk kryptering vil raskt bare virke som et obfuskeringslag, siden man m? ha n?kkelen et sted, og da er man like langt mtp. sikkerhet :)

Vi f?r krysse fingrene for at alt f?r SSO en vakker dag.


Som bruker ville jeg ?nsket meg mulighet for pluggbare moduler for meldingsfunksjonaliteten. Dvs. at man kan skifte fra epost til SMS, eller til Pushover (https://pushover.net), for ? sende varsel om ny sensur. Enda stiligere hvis en slik modul kan byttes ut under kj?ring :)

Dette er hva jeg ville tenkt p? ? implementere, andre har sikkert sine preferanser. Ellers er det saerdeles skjelden at jeg er meldt opp til fag, s? det er i allefall ikke en feature-request! Hehe.



Jo :)

**Comment by fatso83** [comment]
Det er nok en god idé med et modulgrensesnitt. Men så lenge man ikke har
egen server (hvilket gjelder de fleste studenter) er det ikke så mye vits i
å pushe masse tid inn i kjøretidskonfigurasjon, ettersom prosesser blir
kverket automatisk etter ganske kort tid. Daemon-prosesser er altså ikke
noen vei å gå (annet enn som en mulig feature).

1. januar 2015 kl. 09.28 skrev jasama notifications@github.com:
> Et alternativ kan vaere ? lese inn brukernavn og passord interaktivt p?
> start, og deretter g? i daemon-modus. Da slipper man ? lagre brukernavn og
> passord i noe annet medium en minnet. Bakdelen er at man m? starte
> programmet p? nytt manuelt hver gang man snubler i ledningen.
> 
> (A)symmetrisk kryptering vil raskt bare virke som et obfuskeringslag,
> siden man m? ha n?kkelen et sted, og da er man like langt mtp. sikkerhet :)
> 
> Vi f?r krysse fingrene for at alt f?r SSO en vakker dag.
> 
> Som bruker ville jeg ?nsket meg mulighet for pluggbare moduler for
> meldingsfunksjonaliteten. Dvs. at man kan skifte fra epost til SMS, eller
> til Pushover (https://pushover.net), for ? sende varsel om ny sensur.
> Enda stiligere hvis en slik modul kan byttes ut under kj?ring :)
> 
> Dette er hva jeg ville tenkt p? ? implementere, andre har sikkert sine
> preferanser. Ellers er det saerdeles skjelden at jeg er meldt opp til fag,
> s? det er i allefall ikke en feature-request! Hehe.
> 
> Jo :)

**Comment by tobiasvl** [comment]
1. april oppgraderes StudentWeb igjen, noe som høyst sannsynlig vil brekke skriptet: http://www.uio.no/studier/beskjeder/ny-studentweb.html

**Comment by fatso83** [comment]
"Denne nettsiden er ikke publisert"

**Comment by tobiasvl** [comment]
Jeg arkiverer dette repoet, er nok bedre om noen andre lager noe som funker.
